### PR TITLE
MAX_DAYS = 30

### PR DESCRIPTION
**Pull request by psytester**
For most contacts it is annoying that at least all 7 day the auto reply is generated
This PR sets to max 31 days

### CODE REVIEW

**Comment by adeekshith** [comment]
At some other place in the database code, it is hardcoded to store logs for only 30 days as far as I remember so setting `MAX_DAYS` to 31 may not work I guess.
Adding @spuday90 for comment.

**Comment by spuday90** [comment]
Yes as we are purging db for 30days, so MAX_DAYS  cannot exceed that.

**Comment by adeekshith** [comment]
@psytester Can you update it to 30 please 😊

**Comment by psytester** [comment]
done

**Review by adeekshith — APPROVED** [review]

**Pull request merged**
