### PR TITLE
Donation progress improvements (Little sloppy)

### PR DESCRIPTION
**Pull request by adeekshith**
Added goal percentage on top, changed strings.

But left some rough edges which needs to be fixed before merging to `main`:
  - [x] Remove hardcoded strings in fragment_donations.xml - 64599c5
  - [ ] This line in DonationFragment.kt `fragmentView.donation_pct.text = percentReceived.roundToInt().toString() + "%"` should be fixed to make it work for localizations.

Merges to PR #336

Screen Shot 2021-07-02 at 2 24 48 PM

### CODE REVIEW

**Comment by adeekshith** [comment]
Awesome @spuday90 
You can merge it if you approved

**Comment by spuday90** [comment]
@adeekshith  Do we need localization for percentage text as its just number?

**Comment by adeekshith** [comment]
> @adeekshith  Do we need localization for percentage text as its just number?

Numbers get localized too. For example in Arabic.

But fine, not a priority. If not convinient, we can ignore for now.

**Comment by adeekshith** [comment]
> > @adeekshith  Do we need localization for percentage text as its just number?
> 
> Numbers get localized too. For example in Arabic.
> 
> But fine, not a priority. If not convinient, we can ignore for now. 

Like here:

**Pull request merged**
