### PR TITLE
Move contact selector to fragment

### PR DESCRIPTION
**Pull request by hegocre**
Fixes part of #318 

As a side note, `save_menu.xml` could also be used for moving save button to appbar on reply editor activity.

### CODE REVIEW

**Comment by adeekshith** [comment]
Very nice 😃! Thank you @hegocre 

- [ ] Can we auto save selected contacts without clicking on the save button (may be we need a listener)?

> save_menu.xml could also be used for moving save button to appbar on reply editor activity

😊👍

and yayy more Kotlin!!

**Comment by hegocre** [comment]
> Can we auto save selected contacts without clicking on the save button (may be we need a listener)?
The idea of having to save it manually was to be able to change contacts with the ability to undoing by just going back. 
What we can do is every time the users tries to go back and exit the activity, a dialog appears asking whether the user wants to save or discard changes.

**Comment by adeekshith** [comment]
> What we can do is every time the users tries to go back and exit the activity, a dialog appears asking whether the user wants to save or discard changes.

Dialog idea sounds good! May be we can merge this now and do the dialog change in another iteration.

Also made a layout change in #327

**Review by adeekshith — APPROVED** [review]

**Comment by hegocre** [comment]
> Dialog idea sounds good! May be we can merge this now and do the dialog change in another iteration.

Nice! Maybe add it as a task on #318 so we don't forget

**Pull request merged**
