### PR TITLE
Updated docs.

### PR DESCRIPTION
**Pull request by mawoka-myblock**

### CODE REVIEW

**Comment by mawoka-myblock** [comment]
Domains in the language*.js files must be updated

**Comment by mawoka-myblock** [comment]
> Domains in the language*.js files must be updated

Is done

**Comment by adeekshith** [comment]
@mawoka-myblock Did not check the code yet but couple issues I found on https://mawoka-myblock.github.io/watomatic/ :
- Clicking on sidebar links is throwing 404. It is redirecting to `https://mawoka-myblock.github.io/watomatic/#/watomatic/privacy-policy` instead of to `https://mawoka-myblock.github.io/watomatic/#/privacy-policy`
- Clicking on translations page shows an alert dialog: `We will set a cookie if you click ok`
- Do you mind changing the attribution link to your Github URL instead of to external website?
  - Website's SEO can be changed based on the sites that it links to. I trust your website is good but the idea is to set common rules for all contributors including me. In the future we should be able to auto generate from GitHub API or Git commits.

But great work!! Thanks a lot. I'll make a shout out in the groups after merging it 😃

alert-mawoka
404-mawoka

**Comment by mawoka-myblock** [comment]
I mean that the Standard-User won't notice that with the cookie because the user won't change the language over and over

**Comment by mawoka-myblock** [comment]
The problem with the cookie is fixed, but I didn't test it

**Comment by mawoka-myblock** [comment]
For the 404-problem: I don't know at the moment how to fix that

**Comment by mawoka-myblock** [comment]
Also the Sidebar(s) should work (I think)

**Comment by mawoka-myblock** [comment]
I think some links are broken but it is (for me) impossible to change them without the ability to test them. The problem is that `<a href="/watomatic/de"<Deutsch</a>` links there: domain.tld/watomatic/de and it doesn't matter where you are. At markdown, if you are on domain.tld/watomatic and you have a markdown-link `[Deutsch](/watomatic//de)` goes to domain.tld/watomatic/watomatic/de and not to domain.tld/watomatic/de which is the problem

**Comment by mawoka-myblock** [comment]
Sorry, @OpenWarp, that I mentioned OpenWrap, but in the footer it is roght in a sec

**Review by adeekshith — CHANGES_REQUESTED** [review]
> The problem with the cookie is fixed, but I didn't test it

I still see the Cookie dialog. 

> I think some links are broken but it is (for me) impossible to change them without the ability to test them

This seems to be working when I tested. 👏

Just the cookie dialog needs to go. But if you are busy this week, I'll take a look sometime 😊

**Comment by mawoka-myblock** [comment]
So the Cookie-dialog should go completly? What about GDPR?

**Comment by mawoka-myblock** [comment]
Removed it

**Comment by adeekshith** [comment]
> So the Cookie-dialog should go completly? What about GDPR?

Argh right. Idea was we should use local storage instead of cookie to store preferences so we will not be violating GDPR. But let me merge this for now and will either work on the local storage idea is not difficult or re-enable cookie dialog today.

**Review by adeekshith — APPROVED** [review]

**Comment by mawoka-myblock** [comment]
@adeekshith is local storage really gdpr-compliant? If so, it would take 30 seconds to change from cookies to local storage. Let me have a look at it tomorrow

**Comment by adeekshith** [comment]
> @adeekshith is local storage really gdpr-compliant? 

Not in all cases but in our case it is GDPR and CCPA compilant as we are not transmitting info from local storage to the server. Whereas, info in the cookie is passed on to the server with every request.

Not totally sure but I also think we are already GDPR compliant even with the cookie because user language is not technically a personal information and also GDPR allows storing/collecting personal information if it is ONLY used to enhance user experience. But I am sure local storage in our case is compliant as we are not sending user preference back to the server.

> If so, it would take 30 seconds to change from cookies to local storage. Let me have a look at it tomorrow

Awesome! 😃
Will file an issue for you.

**Pull request merged**
