### PR TITLE
Move atrribution option from editor screen to settings

### LINKED ISSUE #301: Move "Add attribution" option to "Settings"
Give an option to remove the attribution which is appending in auto reply message in settings page.

### PR DESCRIPTION
**Pull request by spuday90**
closes #301

### CODE REVIEW

**Comment by adeekshith** [comment]
- [x] Resolved conflicts.
- [ ] Make Attribution ON by default

**Comment by spuday90** [comment]
>     * [x]  Resolved conflicts.
> 
>     * [ ]  Make Attribution ON by default

For fresh install it is working fine

**Comment by adeekshith** [comment]
> >     * [x]  Resolved conflicts.
> > 
> >     * [ ]  Make Attribution ON by default
> 
> For fresh install it is working fine

Checked it on the other or #305 which has these changes and it is not ON by default

**Comment by hegocre** [comment]
I see you removed the `Append Watomatic attribution to help spread the word` checkbox from CustomReplyEditorActivity, but as @spuday90 mentioned https://github.com/adeekshith/watomatic/issues/301#issuecomment-852694956, I think that's the obvious place it should be. I suggest we leave it while also adding the switch on settings. Maybe moving the checkbox above the `SAVE` button will make it easier to find.

**Comment by adeekshith** [comment]
> I see you removed the `Append Watomatic attribution to help spread the word` checkbox from CustomReplyEditorActivity, but as @spuday90 mentioned [#301 (comment)](https://github.com/adeekshith/watomatic/issues/301#issuecomment-852694956), I think that's the obvious place it should be. I suggest we leave it while also adding the switch on settings. Maybe moving the checkbox above the `SAVE` button will make it easier to find.

1. I thought it is the right place too but not many are finding it there. Somehow many are expecting it in the settings. Also for some, it gets hidden below the keyboard esp for small screens or when text is long. 
2.  Moving it above "SAVE" will make it easy to find but it can hide the Save button below the keyboard which is not good.
3. In fact, was thinking of moving the save button also to the action bar (top right) in the future so we can free up some space in the editor activity for reply rules feature (containing filters like if incoming has keywords, etc).
4. Let us show one setting only at one place unless if it is critical.

But for the sake of transparency, we can show a preview of how it looks while saving the text and perhaps include the checkbox in the preview.

Also, guiding them to the setting in editor screen also is not easy as it requires multiple screenshots and lots of explanation like asking them to lower the keyboard if not visible, etc. Just asking them to check in the settings is easy. Lets see how users take this change and go forward accordingly.

**Comment by hegocre** [comment]
> I think this is one of those where we feel it is obvious once we already know where it is but rest of the folks are having trouble finding it.

Yeah, it could be that!

> But for the sake of transparency, we can show a preview of how it looks while saving the text and perhaps include the checkbox in the preview.

I think this will be very important in case we finally remove the checkbox. Some users might not check settings and simply enable the app from the main activity, and then find the attribution text is being added. I think that would be very confusing.

**Comment by adeekshith** [comment]
> I think this will be very important in case we finally remove the checkbox. Some users might not check settings and simply enable the app from the main activity, and then find the attribution text is being added. I think that would be very confusing.

Okay, lets leave the checkbox as-is until we figure out a better way 😊

**Comment by spuday90** [comment]
> > > ```
> > > * [x]  Resolved conflicts.
> > > 
> > > * [ ]  Make Attribution ON by default
> > > ```
> > 
> > 
> > For fresh install it is working fine
> 
> Checked it on the other PR #305 which has these changes and it is not ON by default

@adeekshith this is happening because on our devices as we have app installed from store its not considering as first install. Please check on other device.

**Comment by adeekshith** [comment]
> @adeekshith this is happening because on our devices as we have app installed from store its not considering as first install. Please check on other device.

Seem to be working on the other PR but may need some more UI improvements before merging this. We can keep the branch but lets close this PR until we figure out the UI 😊

**Pull request closed without merging**
