### PR TITLE
ptbr translation

### PR DESCRIPTION
**Pull request by mezysinc**
strings in ptbr 🚀 🌕

### CODE REVIEW

**Review by adeekshith — APPROVED** [review]
Woo hoo! 😃🙌
I do not speak the language myself but Google translate seems to approve. Thanks a lot!

**Comment by adeekshith** [comment]
@mezysinc I really appreciate your contribution! 😃 But if you dont mind me asking, you do really speak Portuguese dont you? All the strings are an exact Google translate match so wanted to confirm.

**Comment by mezysinc** [comment]
Well, in the end AI is scrapping translations from all over the web to feed their algorithms. It learns from ppl. Hopefully it might be useful for someone. Also try to submit it to official fdr. repo.

**Comment by adeekshith** [comment]
Makes sense. Thanks a lot! 😊

> Also try to submit it to official fdr. repo

Sure, making preparations for that and should be in the main F-Droid repo soon

**Pull request merged**
