### PR TITLE
[WIP] Issue/346/fix code warnings

### PR DESCRIPTION
**Pull request by hegocre**
This needs testing to check everything works as before (did a little of testing myself and everything seems right). Also some files need more corrections, which I didn't do, as they are some unused functions or variables which I don't know if they are intended to use later.

### CODE REVIEW

**Comment by hegocre** [comment]
Some things related to this PR:

* Adding and removing custom contacts is now animated, as it's not using `notifyDataSetChanged()` anymore.
* The donations percentage is not loading, looks like [`https://home.deekshith.in/tmp/donations.txt`](https://home.deekshith.in/tmp/donations.txt) is down.

**Comment by adeekshith** [comment]
> The donations percentage is not loading, looks like https://home.deekshith.in/tmp/donations.txt is down (did not want to open an issue for this since it's not directly related to this repository).

Yeah, I moved to a different apartment recently and my my building internet is not allowing port forwarding so my home server is currently down 🙁

Will better upload donations data from GitHub pages itself.

**Review by spuday90 — CHANGES_REQUESTED** [review]
Reviewed the code so far looks good, as @hegocre mentioned still there are some minor corrections needed here and there better to fix them all.

Didn't test the app yet will do.

**Comment by hegocre** [comment]
> if getActivity is null this line can also crash, please move this inside if condition

Done! Also merged main into this

**Review by spuday90 — COMMENTED** [review]
Observed one issue in contacts selector. In add custom contact name popup if u press ok without entering any text it is showing empty text at the top attached screenshot for the same, please put a non empty check there. 
Rest Everything looks good.
Screenshot_2021-08-19-08-13-27-264_com parishod watomatic

**Comment by hegocre** [comment]
> Observed one issue in contacts selector. In add custom contact name popup if u press ok without entering any text it is showing empty text at the top attached screenshot for the same, please put a non empty check there.
Rest Everything looks good.

Nice catch there! Opened a separate issue as it's not related to this PR. #354

**Comment by adeekshith** [comment]
@hegocre this still has the `PR-DO-NOT-MERGE` tag. Is this good to go?

**Comment by hegocre** [comment]
> @hegocre this still has the `PR-DO-NOT-MERGE` tag. Is this good to go?

For me it is, I was waiting for you as well as @spuday90 to fix some warnings like unused functions since I don't know if they will be needed.

**Review by spuday90 — APPROVED** [review]

**Pull request merged**
