### PR TITLE
Updated German translations strings.xml

### PR DESCRIPTION
**Pull request by daengi**
Improved the German translations in strings.xml

### CODE REVIEW

**Comment by adeekshith** [comment]
Thanks for your contribution @daengi 😃
But in the future, please consider joining us on Crowdin and add language contributions there: https://crowdin.com/project/watomatic 

It will be easy for the reviewers.

Thank you!!

**Comment by daengi** [comment]
Oh, sorry. I didn't know that. The next time I will do that! 😄

**Comment by adeekshith** [comment]
> Oh, sorry. I didn't know that. The next time I will do that! 😄

Oh no probs! Thank you! 😊

**Comment by daengi** [comment]
You're welcome! 😊

**Review by mawoka-myblock — CHANGES_REQUESTED** [review]
Maybe replace "Klick" through "Tipp" (or so) because you don't click on a phone. The rest is great!

**Comment by daengi** [comment]
Yes, I'll change it to "Tippe".

**Comment by daengi** [comment]
Done! 😊

**Review by mawoka-myblock — APPROVED** [review]
Nice!

**Pull request merged**
